#!/usr/bin/env python3
from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]
WF=ROOT/'.github/workflows/youtube-shorts.yml'
VS=ROOT/'scripts/visual_candidate_select.py'

def replace_once(text, old, new, label):
    if old not in text:
        raise RuntimeError(f'patch anchor missing: {label}')
    return text.replace(old,new,1)

def patch_workflow():
    s=WF.read_text(encoding='utf-8')
    s=replace_once(s,'      GEMINI_MODEL: gemini-3.6-flash\n','      GEMINI_MODEL: gemini-3.6-flash\n      GEMINI_IMAGE_API_KEY: ${{ secrets.GEMINI_IMAGE_API_KEY }}\n      GEMINI_IMAGE_MODEL: gemini-3.1-flash-image\n      ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}\n      ELEVENLABS_MODEL: eleven_v3\n      ELEVENLABS_VOICE_ID: JBFqnCBsd6RMkjVDRZzb\n      ELEVENLABS_STABILITY: "0.30"\n      ELEVENLABS_SIMILARITY: "0.75"\n      ELEVENLABS_STYLE: "0.65"\n      ELEVENLABS_SPEED: "1.0"\n      CARTESIA_API_KEY: ${{ secrets.CARTESIA_API_KEY }}\n      CARTESIA_MODEL: sonic-3.5\n      CARTESIA_VOICE_ID: f786b574-daa5-4673-aa0c-cbe3e8534c02\n', 'provider env')
    s=replace_once(s,'          if [[ -z "${TOGETHER_API_KEY:-}" ]]; then echo "::warning::TOGETHER_API_KEY is not configured; provider 5 will be skipped."; fi\n          (( missing == 0 ))','          if [[ -z "${TOGETHER_API_KEY:-}" ]]; then echo "::warning::TOGETHER_API_KEY is not configured; provider 5 will be skipped."; fi\n          if [[ -z "${ELEVENLABS_API_KEY:-}" ]]; then echo "::warning::ELEVENLABS_API_KEY is not configured; expressive TTS will fall back."; fi\n          if [[ -z "${CARTESIA_API_KEY:-}" ]]; then echo "::warning::CARTESIA_API_KEY is not configured; secondary TTS will be skipped."; fi\n          if [[ -z "${GEMINI_IMAGE_API_KEY:-}" ]]; then echo "::warning::GEMINI_IMAGE_API_KEY is not configured; AI visual fallback will be unavailable."; fi\n          (( missing == 0 ))','secret warnings')
    s=replace_once(s,'      - name: Validate repository scripts\n','      - name: Enable expressive TTS router\n        shell: bash\n        run: |\n          set -Eeuo pipefail\n          chmod +x scripts/voice_router.sh\n          echo "KOKORO_BIN=$GITHUB_WORKSPACE/scripts/voice_router.sh" >> "$GITHUB_ENV"\n\n      - name: Validate repository scripts\n','tts router step')
    s=replace_once(s,'      - name: Production content and Pexels preflight\n','      - name: Conversational Voice Director\n        shell: bash\n        run: |\n          set -Eeuo pipefail\n          python scripts/voice_director.py\n          jq \"{voice_style,hook,scene_count:(.scenes|length),script_words:(.script|split(\\\" \\\")|length)}\" \"$RUN_DIR/job.json\"\n\n      - name: Production content and Pexels preflight\n','voice director step')
    WF.write_text(s,encoding='utf-8')

def patch_visual_selector():
    s=VS.read_text(encoding='utf-8')
    anchor='def main():\n'
    fn='''def gemini_image_fallback(narration, subject, role, output, scene_index):\n import base64, json, urllib.request, subprocess, tempfile\n key=os.environ.get("GEMINI_IMAGE_API_KEY","").strip()\n if not key: return False, "GEMINI_IMAGE_API_KEY missing"\n model=os.environ.get("GEMINI_IMAGE_MODEL","gemini-3.1-flash-image")\n prompt=(f"Create a vertical 9:16 educational visual that clearly explains this narration: {narration}. "\n         f"Main subject: {subject}. Required evidence: {role}. "\n         "Use a clean premium science-explainer style, realistic or accurate illustration as appropriate, "\n         "strong visual hierarchy, one main concept, no decorative clutter, no Arabic/English captions, no watermark-like text, "\n         "and make the visual evidence directly demonstrate the claim rather than merely depicting the topic.")\n body={"model":model,"input":[{"type":"text","text":prompt}],"response_format":{"type":"image","mime_type":"image/png","aspect_ratio":"9:16","image_size":"1K"}}\n req=urllib.request.Request("https://generativelanguage.googleapis.com/v1beta/interactions",data=json.dumps(body).encode(),headers={"x-goog-api-key":key,"Content-Type":"application/json"},method="POST")\n with urllib.request.urlopen(req,timeout=180) as r: payload=json.loads(r.read().decode("utf-8","replace"))\n image=None\n for step in payload.get("steps",[]):\n  for block in step.get("content",[]) if isinstance(step,dict) else []:\n   if isinstance(block,dict) and block.get("type")=="image" and block.get("data"): image=base64.b64decode(block["data"]); break\n  if image: break\n if not image and isinstance(payload.get("output_image"),dict) and payload["output_image"].get("data"): image=base64.b64decode(payload["output_image"]["data"])\n if not image: return False, "Gemini returned no image"\n png=Path(str(output)+".gemini.png"); png.write_bytes(image)\n subprocess.run(["ffmpeg","-hide_banner","-loglevel","error","-y","-loop","1","-i",str(png),"-t","12","-vf","scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,zoompan=z='min(zoom+0.0007,1.08)':x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':d=1:s=1080x1920:fps=30,format=yuv420p","-an","-c:v","libx264","-preset","veryfast","-crf","20","-pix_fmt","yuv420p",str(output)],check=True)\n png.unlink(missing_ok=True)\n return True, "gemini-image"\n\n'''
    if 'def gemini_image_fallback(' not in s:
        s=s.replace(anchor,fn+anchor,1)
    old='''  elif ALLOW_DETERMINISTIC_FALLBACK:\n   chosen,vid=deterministic_pick(usable,a.output,idx); score=0.0; semantic=0.0; mode='deterministic-fallback'\n  else:\n   print(json.dumps({'error':'vision selection unavailable','provider_errors':errors},ensure_ascii=False)); return 1\n  Path(a.output).parent.mkdir(parents=True,exist_ok=True); shutil.copyfile(chosen,a.output); meta=Path(a.output).with_suffix('.selection.json')\n'''
    new='''  elif os.environ.get('GEMINI_IMAGE_API_KEY','').strip():\n   try:\n    ok,reason=gemini_image_fallback(a.narration,a.visual_subject,role,a.output,idx)\n    if ok:\n     score=0.90; semantic=0.90; mode='gemini-image-fallback'; chosen=None; vid=None; provider='Gemini Image'\n    else:\n     raise RuntimeError(reason)\n   except Exception as e:\n    errors.append(f'Gemini Image: {e}')\n    if ALLOW_DETERMINISTIC_FALLBACK:\n     chosen,vid=deterministic_pick(usable,a.output,idx); score=0.0; semantic=0.0; mode='deterministic-fallback'\n    else:\n     print(json.dumps({'error':'visual selection unavailable','provider_errors':errors},ensure_ascii=False)); return 1\n  elif ALLOW_DETERMINISTIC_FALLBACK:\n   chosen,vid=deterministic_pick(usable,a.output,idx); score=0.0; semantic=0.0; mode='deterministic-fallback'\n  else:\n   print(json.dumps({'error':'vision selection unavailable','provider_errors':errors},ensure_ascii=False)); return 1\n  if mode == 'gemini-image-fallback':\n   meta=Path(a.output).with_suffix('.selection.json')\n   meta.write_text(json.dumps({'query':search_query,'requested_query':a.query,'visual_subject':a.visual_subject,'shot_role':role,'selected_video_id':None,'candidate_count':len(candidates),'selection_score':score,'semantic_score':semantic,'provider':'Gemini Image','fallback':True,'reason':'Generated a purpose-built explanatory visual after Pexels candidates failed strict semantic selection.','provider_errors':errors},ensure_ascii=False,indent=2),encoding='utf-8')\n   print(f'Generated AI explanatory visual query={search_query!r} score={score:.2f} semantic={semantic:.2f} mode=gemini-image-fallback',flush=True)\n   return 0\n  Path(a.output).parent.mkdir(parents=True,exist_ok=True); shutil.copyfile(chosen,a.output); meta=Path(a.output).with_suffix('.selection.json')\n'''
    if old not in s: raise RuntimeError('visual fallback anchor missing')
    s=s.replace(old,new,1)
    VS.write_text(s,encoding='utf-8')

def main():
    patch_workflow(); patch_visual_selector(); print('expressive pipeline patches installed')
if __name__=='__main__': main()
